#include "pomp_lib.h"

struct ompregdescr omp_rd_1 = {
  "parallel", "", 0, "stencil_cpu.cpp", 43, 43, 61, 61
};

#define POMP_DLIST_00001 shared(omp_rd_1)

struct ompregdescr omp_rd_2 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 79, 79, 82, 82
};

#define POMP_DLIST_00002 shared(omp_rd_2)

struct ompregdescr omp_rd_3 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 87, 87, 90, 90
};

#define POMP_DLIST_00003 shared(omp_rd_3)

struct ompregdescr omp_rd_4 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 94, 94, 97, 97
};

#define POMP_DLIST_00004 shared(omp_rd_4)

struct ompregdescr omp_rd_5 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 115, 115, 125, 125
};

#define POMP_DLIST_00005 shared(omp_rd_5)

struct ompregdescr omp_rd_6 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 142, 142, 152, 152
};

#define POMP_DLIST_00006 shared(omp_rd_6)

struct ompregdescr omp_rd_7 = {
  "parallelfor", "", 0, "stencil_cpu.cpp", 170, 170, 180, 180
};

#define POMP_DLIST_00007 shared(omp_rd_7)

